services:
    jenkins:
        build: ./jenkins/master
        image: jenkins-jb/master:1.0
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        networks: 
            - jb
    jenkins-slave:
        build: ./jenkins/slave
        image: jenkins-jb/slave:1.0
        # Removed container name to support scale out option 
        #container_name: jenkins-slave 
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        ports:
            - "5005-5010:5005-5010"

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - ./volume:/home/jenkins # Avoid mysql volume mount issue
        networks: 
        - jb
        depends_on:
            - jenkins

networks: 
  jb: